[package]
name = "kl_lords"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.18.1", features = ["dynamic_linking"] }
bevy_voxel_world = "0.16.0"
noise = "0.9.0"
noiz = "0.4.0"
rand = "0.10.1"

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 2
debug = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3
